# Generated by Django 4.2.5 on 2023-09-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название сайта')),
                ('assress', models.CharField(max_length=500, verbose_name='Адрес')),
            ],
        ),
    ]
