# Generated by Django 4.2.5 on 2023-09-29 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_settings_email_settings_facebook_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'настройки', 'verbose_name_plural': 'настройка'},
        ),
    ]
