# Generated by Django 4.2.5 on 2023-09-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_program', models.TextField(verbose_name='школьная программа')),
            ],
            options={
                'verbose_name': 'программа',
            },
        ),
    ]
