# Generated by Django 4.2.5 on 2023-09-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our_teachers', models.TextField(verbose_name='Наши учетеля')),
            ],
            options={
                'verbose_name': 'учителя',
            },
        ),
    ]
